### ISSUE TITLE
Level Scaling Not Working

### ISSUE THREAD

**Issue by ItsDrafty** [JPMeehan/talent-psionics#8]
Hello! I recently switched over from the other module that seemed to have dropped support. Me and my Talent player noticed that casting Powers at higher level isn't working. 1st-Order powers don't scale and 2nd-Order or higher Powers don't have an option to select  either. Wondering if this is a known issue? Regardless of level, the Power will roll with whatever scaling has been entered. For example, Share Pain is a 2nd-Order Power that deals 1d12, if I have "Increased Order" entered in with 1d12, it always casts at 2d12 and has no option to select what level the Power is cast (reference below)

![image](https://github.com/user-attachments/assets/aaf9a360-020d-4f1e-9040-2f2a1ced632b)
![image](https://github.com/user-attachments/assets/c2f99c64-f6bd-481a-9238-d6a86e4b9fff)

Thanks for all your hard work!

Foundry: V12 Stable (latest)
D&D5e: 3.3.1
Module: 1.1.2 (only module active)

**Comment by JPMeehan** [comment]
Not strictly sure what's happening here but this is made moot by the 4.0 updates
